//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassQuestions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_settings
    {
        public string id { get; set; }
        public string examyearid { get; set; }
        public string examtypeid { get; set; }
        public string amount { get; set; }
        public string per_discount { get; set; }
    
        public virtual examtype examtype { get; set; }
        public virtual examyear examyear { get; set; }
    }
}
