//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassQuestions.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pastquestionEntities : DbContext
    {
        public pastquestionEntities()
            : base("name=pastquestionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<examtype> examtypes { get; set; }
        public virtual DbSet<examyear> examyears { get; set; }
        public virtual DbSet<feesetting> feesettings { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<useraccount> useraccounts { get; set; }
    }
}
