//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassQuestions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public string id { get; set; }
        public string names { get; set; }
        public string description { get; set; }
        public string subjectid { get; set; }
        public string examyearid { get; set; }
        public string examtypeid { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public string photo { get; set; }
        public Nullable<System.DateTime> expdate { get; set; }
        public string status { get; set; }
        public string url { get; set; }
        public string doctype { get; set; }
    
        public virtual examtype examtype { get; set; }
        public virtual examyear examyear { get; set; }
        public virtual subject subject { get; set; }
    }
}
